batch_size: 512
nc: 2
img_channels: 3
epochs: 50
lr: 0.01
image_size: 224
train_csv: ./data/train.csv
test_csv: ./data/test.csv
imgs_path: ./data/images
workers: 8
device: 0
shuffle: True
classes: ['Cat', 'Dog']